# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38fb66428afb8a9c139c1825b01e775c1e1e8f61c34b598f95d24c709045398bfe5fda5901c50dd648918aba43fd8f202c2aca7bcd13cbbaff378f81bbc2e5cc

test:
  secret_key_base: 99af3138e964327efe0fdee4dbf99bf9e2dab9ad433dccdbf1eea59e5033154e57656ffe1cb0da687e3e7e17f963a1e172436e67e1cb0f5c38d4600d52cdd465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
